##
# tests.yaml - Testing workflow.
# Copyright 2021-2022 Adequate Systems, LLC. All Rights Reserved.
#

name: Tests
on:
  push:
    branches: [main]
  pull_request:
    # pull_request branches MUST be a subset of push branches
    branches: [main]
jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Components
        run: make test -C ${{ github.workspace }}
