##
# tests.yaml - Testing workflow.
#
# Copyright 2021-2022 Adequate Systems, LLC. All Rights Reserved.
# For license information, please refer to ../../LICENSE.md
#

name: Tests
on:
  push:
    branches: [main]
  pull_request:
    # pull_request branches MUST be a subset of push branches
    branches: [main]
jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Components
        run: make test -C ${{ github.workspace }}
  coverage:
    runs-on: ubuntu-latest
    needs: [components]
    steps:
      - name: Update apt and install lcov
        run: sudo apt update && sudo apt install -y lcov
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate test coverage
        run: make coverage -C ${{ github.workspace }}
      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v2
